util/u_atomic: unbreak build on compilers without __atomic
Don't provide replacements for 64 bit __atomic builtins if
the compiler does not implement __atomic builtins.

Avoids fatal build errors:
error: no previous prototype for '__atomic_fetch_add_8'
error: no previous prototype for '__atomic_fetch_sub_8'

Signed-off-by: Jonathan Gray <jsg@jsg.id.au>
(cherry picked from commit e47f85b9a8af74fa76c0bdbeb589f7d9780ebe33)