intel/aubinator_error_decode: link libm
aubinator_error_decode needs to link libm to build on i386
../../src/util/.libs/libmesautil.a(libmesautil_la-half_float.o): In function `_mesa_float_to_half':
half_float.c:(.text+0x91): undefined reference to `lrintf'
half_float.c:(.text+0xc1): undefined reference to `lrintf'

Signed-off-by: Jonathan Gray <jsg@jsg.id.au>